<?php
require_once __DIR__ . "/config/db.php";

$leadId = filter_input(INPUT_GET, 'lead_id', FILTER_VALIDATE_INT);
if (!$leadId) {
    $leadId = filter_input(INPUT_POST, 'lead_id', FILTER_VALIDATE_INT);
}

if (!$leadId) {
    $leadId = 1;
}

$stmt = $pdo->prepare("SELECT id, name, email, phone FROM leads WHERE id = ?");
$stmt->execute([$leadId]);
$lead = $stmt->fetch();

if (!$lead) {
    http_response_code(404);
    exit("Lead not found.");
}

$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $note = trim($_POST['note'] ?? '');

    if ($note === '') {
        $errors[] = "Please enter a note.";
    } elseif (mb_strlen($note) > 5000) {
        $errors[] = "Note must be 5000 characters or less.";
    }

    if (!$errors) {
        // created_at is generated by MySQL using the current date/time.
        $insert = $pdo->prepare(
            "INSERT INTO activity_logs (lead_id, activity_type, note, created_at)
             VALUES (?, 'note', ?, NOW())"
        );
        $insert->execute([$leadId, $note]);

        header("Location: activity_history.php?lead_id=" . urlencode((string)$leadId) . "&saved=1");
        exit;
    }
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Save Manual Note - <?= htmlspecialchars($lead['name']) ?></title>
    <style>
        body{font-family:Arial,sans-serif;background:#f4f6f8;margin:0;color:#20252b}
        .container{max-width:720px;margin:50px auto;padding:0 18px}
        .card{background:#fff;border-radius:12px;padding:24px;box-shadow:0 4px 18px rgba(0,0,0,.08)}
        h1{margin-top:0}.lead{background:#f0f3f6;padding:14px;border-radius:8px;margin-bottom:18px}
        label{display:block;font-weight:700;margin-bottom:8px}
        textarea{width:100%;box-sizing:border-box;min-height:150px;padding:12px;border:1px solid #ccd2d8;border-radius:8px;resize:vertical;font:inherit}
        button,.link{display:inline-block;margin-top:14px;padding:11px 16px;border:0;border-radius:8px;text-decoration:none;font-weight:700;cursor:pointer}
        button{background:#222;color:#fff}.link{background:#e8edf2;color:#222;margin-left:8px}
        .error{background:#ffe9e9;color:#a00000;padding:10px;border-radius:8px;margin-bottom:15px}
    </style>
</head>
<body>
<div class="container">
    <div class="card">
        <h1>Save Manual Note</h1>

        <div class="lead">
            <strong>Lead:</strong> <?= htmlspecialchars($lead['name']) ?><br>
            <?php if ($lead['email']): ?>Email: <?= htmlspecialchars($lead['email']) ?><br><?php endif; ?>
            <?php if ($lead['phone']): ?>Phone: <?= htmlspecialchars($lead['phone']) ?><?php endif; ?>
        </div>

        <?php foreach ($errors as $error): ?>
            <div class="error"><?= htmlspecialchars($error) ?></div>
        <?php endforeach; ?>

        <form method="post" action="">
            <input type="hidden" name="lead_id" value="<?= (int)$lead['id'] ?>">

            <label for="note">Note</label>
            <textarea id="note" name="note" maxlength="5000"
                      placeholder="e.g. Called, no answer" required><?= htmlspecialchars($_POST['note'] ?? '') ?></textarea>

            <button type="submit">Save Note</button>
            <a class="link" href="activity_history.php?lead_id=<?= (int)$lead['id'] ?>">View Activity History</a>
        </form>
    </div>
</div>
</body>
</html>
